version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: sql-batch-practice-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: practice_db
    ports:
      - "15432:5432"
    volumes:
      - ./infra/postgres/data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
